# Generated by Django 3.1 on 2020-08-05 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiproduct', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='available',
            new_name='status',
        ),
    ]
