# Generated by Django 3.1 on 2020-08-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiproduct', '0002_auto_20200805_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imageUrl',
            field=models.URLField(default='aws.reqre.in/producs/image000001.jpg'),
        ),
    ]
