# Generated by Django 3.1 on 2020-08-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiproduct', '0004_product_product_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=25)),
                ('pages', models.IntegerField()),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('description', models.TextField()),
                ('imageUrl', models.URLField(default='aws.reqre.in/producs/image000001.jpg')),
                ('status', models.BooleanField(choices=[(0, 'Unavailable'), (1, 'Available')])),
            ],
        ),
    ]
